services:
  - type: web
    name: tickr-v14
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd tickr_website && gunicorn server:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
